// 表单配置
export const formConf = {
  formRef: 'formRef',
  formModel: 'formData',
  size: 'middle' as const,
  labelWidth: 100,
  formRules: 'rules',
  gutter: 15,
  disabled: false,
  span: 24,
  formBtns: true,
}

// 输入型组件配置
export const inputComponents = [
  {
    label: '单行文本',
    tag: 'Input',
    tagIcon: 'input',
    type: 'text',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    allowClear: true,
    addonBefore: '',
    addonAfter: '',
    prefix: null,
    suffix: null,
    maxLength: null,
    showCount: false,
    readOnly: false,
    disabled: false,
    required: true,
  },
  {
    label: '多行文本',
    tag: 'Input.TextArea',
    tagIcon: 'textarea',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    autoSize: { minRows: 4, maxRows: 4 },
    style: { width: '100%' },
    maxLength: null,
    showCount: false,
    readOnly: false,
    disabled: false,
    required: true,
  },
  {
    label: '密码',
    tag: 'Input.Password',
    tagIcon: 'password',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    allowClear: true,
    readOnly: false,
    disabled: false,
    required: true,
  },
  {
    label: '数字输入',
    tag: 'InputNumber',
    tagIcon: 'number',
    placeholder: '',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    precision: undefined,
    disabled: false,
    required: true,
  },
]

// 选择型组件配置
export const selectComponents = [
  {
    label: '下拉选择',
    tag: 'Select',
    tagIcon: 'select',
    placeholder: '请选择',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    allowClear: true,
    disabled: false,
    required: true,
    showSearch: false,
    mode: 'multiple' as const,
    options: [
      { label: '选项一', value: 1 },
      { label: '选项二', value: 2 },
    ],
  },
  {
    label: '单选框组',
    tag: 'Radio.Group',
    tagIcon: 'radio',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: {},
    optionType: 'default' as const,
    buttonStyle: 'outline' as const,
    size: 'middle' as const,
    disabled: false,
    required: true,
    options: [
      { label: '选项一', value: 1 },
      { label: '选项二', value: 2 },
    ],
  },
  {
    label: '多选框组',
    tag: 'Checkbox.Group',
    tagIcon: 'checkbox',
    defaultValue: [],
    span: 24,
    labelWidth: null,
    style: {},
    optionType: 'default' as const,
    size: 'middle' as const,
    disabled: false,
    required: true,
    options: [
      { label: '选项一', value: 1 },
      { label: '选项二', value: 2 },
    ],
  },
  {
    label: '开关',
    tag: 'Switch',
    tagIcon: 'switch',
    defaultValue: false,
    span: 24,
    labelWidth: null,
    style: {},
    disabled: false,
    required: true,
    checkedChildren: '',
    unCheckedChildren: '',
  },
  {
    label: '滑块',
    tag: 'Slider',
    tagIcon: 'slider',
    defaultValue: 0,
    span: 24,
    labelWidth: null,
    disabled: false,
    required: true,
    min: 0,
    max: 100,
    step: 1,
    dots: false,
    range: false,
  },
  {
    label: '时间选择',
    tag: 'TimePicker',
    tagIcon: 'time',
    placeholder: '请选择',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    allowClear: true,
    required: true,
    format: 'HH:mm:ss',
  },
  {
    label: '日期选择',
    tag: 'DatePicker',
    tagIcon: 'date',
    placeholder: '请选择',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    allowClear: true,
    required: true,
    format: 'YYYY-MM-DD',
  },
  {
    label: '日期范围',
    tag: 'DatePicker.RangePicker',
    tagIcon: 'date-range',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    allowClear: true,
    required: true,
    format: 'YYYY-MM-DD',
  },
  {
    label: '评分',
    tag: 'Rate',
    tagIcon: 'rate',
    defaultValue: 0,
    span: 24,
    labelWidth: null,
    style: {},
    max: 5,
    allowHalf: false,
    showText: false,
    disabled: false,
    required: true,
  },
  {
    label: '颜色选择',
    tag: 'ColorPicker',
    tagIcon: 'color',
    defaultValue: null,
    labelWidth: null,
    disabled: false,
    required: true,
    showText: false,
  },
  {
    label: '上传',
    tag: 'Upload',
    tagIcon: 'upload',
    action: 'https://jsonplaceholder.typicode.com/posts/',
    defaultValue: null,
    labelWidth: null,
    disabled: false,
    required: true,
    accept: '',
    name: 'file',
    withCredentials: false,
    showUploadList: true,
    listType: 'text' as const,
    multiple: false,
    tip: '',
    style: { width: '100%' },
  },
]

// 布局型组件配置
export const layoutComponents = [
  {
    layout: 'rowFormItem',
    tagIcon: 'row',
    type: 'default',
    justify: 'start',
    align: 'top',
    label: '行容器',
    layoutTree: true,
    children: [],
    gutter: 15,
  },
  {
    layout: 'colFormItem',
    label: '按钮',
    labelWidth: null,
    tag: 'Button',
    tagIcon: 'button',
    span: 24,
    default: '主要按钮',
    type: 'primary' as const,
    icon: 'SearchOutlined',
    size: 'middle' as const,
    disabled: false,
  },
]

// 组件 rule 的触发方式
export const trigger: Record<string, string> = {
  Input: 'onChange',
  InputNumber: 'onChange',
  Select: 'onChange',
  'Radio.Group': 'onChange',
  'Checkbox.Group': 'onChange',
  TimePicker: 'onChange',
  DatePicker: 'onChange',
  Rate: 'onChange',
}
